name: Postman CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run CURD.postman_collection.json --reporters cli,htmlextra --reporter-htmlextra-export report.html

      - name: Store Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: path/to/report.html
