name: Postman CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3.2.0
        with:
         node-version: '16'

      - name: Install Newman
        run: |
           npm install -g newman newman-reporter-htmlextra
        

      - name: Run Postman Collection
        run: newman run CURD.postman_collection.json --reporters cli,htmlextra --reporter-htmlextra-export report.html

      - name: Store Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.html
          retention-days: 30
          
